kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: jupyter/pyspark-notebook
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
#          resources:
#            requests:
#              cpu: 100m

---
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark
      port: 7077
      targetPort: 7077
  selector:
    component: spark-master    

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spark-ingress
  annotations:
spec:
  rules:
  - host: spark-kubernetes
    http:
      paths:
      - path: /
        backend:
          serviceName: spark-master
          servicePort: 8080    