apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-interface-deployment
  labels:
    app: my-interface-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myexpressapp
  template:
    metadata:
      labels:
        app: myexpressapp
    spec:
      # This uses our app container image
      # Works for minikube only since we didn't publish the image
      containers:
        - name: myexpressapp
          image: interface
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: my-interface-service
spec:
  selector:
    app: myexpressapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-webapp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: my-interface-service
              servicePort: 8080