apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: spark-scheduled
  namespace: default
spec:
  schedule: "@every 5m"
  concurrencyPolicy: Allow
  template:
    type: Python
    mode: cluster
    image: "gcr.io/spark-operator/spark:v2.4.5"
    imagePullPolicy: Always
    mainApplicationFile: "local:///Users/shabaldinalidiia/git/Big-Data/pyspark-app/pyspark_driver.py"
    sparkVersion: "2.4.5"
    restartPolicy:
      type: Never
    driver:
      cores: 1
      coreLimit: "1200m"
      memory: "512m"
      labels:
        version: 2.4.5
      serviceAccount: spark
    executor:
      cores: 1
      instances: 1
      memory: "512m"
      labels:
        version: 2.4.5